{{- if and (not .Values.rejseplanen.existingSecret) .Values.rejseplanen.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cph-metro-exporter.fullname" . }}
  labels:
    {{- include "cph-metro-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.rejseplanen.apiKey | b64enc | quote }}
{{- end }}
